### ISSUE TITLE
6.1 Update

### ISSUE THREAD

**Issue by Nerothos** [Asvel/ffxiv-lodestone-item-id#1]
Hi, could you update it for 6.1?
I tried the script but it only downloaded around 600 pages.

**Comment by Asvel** [comment]
Updated, I forgot to update it, sorry for this delay.

**Comment by Nerothos** [comment]
No problem, thanks so much !
Could you perhaps share the pages you already so we could do it on our own without flooding the lodestone servers with existing one?

**Comment by Asvel** [comment]
I think it is not proper to commit these pages it into git repo, so I upload them here.
[lodestone-pages-6.1.zip](https://github.com/Asvel/ffxiv-lodestone-item-id/files/8525445/lodestone-pages-6.1.zip)

**Comment by Nerothos** [comment]
Thanks !
